### ISSUE TITLE
NameError: global name 'device' is not defined

### ISSUE THREAD

**Issue by DavidHenryM** [null-none/python-dymo-scale#1]
Line 17 of scale.py appears to have an error:
`self.endpoint = device[0][(0,0)][0]`
should read...
`self.endpoint = self.device[0][(0,0)][0]`
after changing this I had no issue

**Comment by null-none** [comment]
@DavidHenryM Your printer is turned on?

**Comment by toastedtoast** [comment]
+1 
can you please modify line 17 in scale.py to
`self.endpoint = self.device[0][(0,0)][0]`
as @DavidHenryM suggested. Your script does not run currently. 

Additionally I want to thank you for wrapping this code into a library.

**Comment by null-none** [comment]
@DavidHenryM @toastedtoast thank you!
